#!/bin/bash -l

#PBS -P LSTO
#PBS -N elast_comp_MPI_3D

#PBS -l select=125:ncpus=1:mpiprocs=1:ompthreads=1:mem=8GB:cputype=6140
#PBS -l walltime=23:00:00
#PBS -j oe
#PBS -v I_MPI_HYDRA_BOOTSTRAP=rsh
#PBS -v I_MPI_HYDRA_BOOTSTRAP_EXEC=pbs_tmrsh
#PBS -v I_MPI_HYDRA_IFACE=ib0
#PBS -v OMP_NUM_THREADS=1

source $HOME/hpc-environments-main/lyra/load-intel.sh
PROJECT_DIR=$HOME/LevelSetTopOpt/

julia --project=$PROJECT_DIR -e "using Pkg; Pkg.precompile()"

mpirun -n 125 julia --project=$PROJECT_DIR --check-bounds no -O3 --compiled-modules=no \
  $PROJECT_DIR/scripts/_dev/Paper_scripts/elast_comp_MPI_3D.jl
