#!/bin/bash -l

#PBS -P LSTO
#PBS -N hyperelast_comp_MPI_3D

#PBS -l select=125:ncpus=1:mpiprocs=1:ompthreads=1:mem=8GB:cputype=6140
#PBS -l walltime=23:00:00
#PBS -j oe

source $HOME/hpc-environments-main/lyra/load-ompi.sh
PROJECT_DIR=$HOME/LevelSetTopOpt/

julia --project=$PROJECT_DIR -e "using Pkg; Pkg.precompile()"

mpirun --hostfile $PBS_NODEFILE \
 julia --project=$PROJECT_DIR --check-bounds no -O3 --compiled-modules=no \
  $PROJECT_DIR/scripts/_dev/Paper_scripts/hyperelast_comp_MPI_3D.jl
