#!/bin/bash -l
#PBS -P LSTO
#PBS -N 3d_inverter_HPM

#PBS -l select=125:ncpus=1:mpiprocs=1:ompthreads=1:mem=8GB:cputype=6140
#PBS -l walltime=50:00:00
#PBS -j oe

source $HOME/hpc-environments-main/lyra/load-ompi.sh
PROJECT_DIR=$HOME/LevelSetTopOpt/

julia --project=$PROJECT_DIR -e "using Pkg; Pkg.precompile()"

mpirun --hostfile $PBS_NODEFILE \
 julia --project=$PROJECT_DIR --check-bounds no -O3 --compiled-modules=no \
  $PROJECT_DIR/scripts/MPI/3d_inverter_HPM.jl
